apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: criado-via-yaml
  namespace: fiapaso6-rodrigo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blog-django-py3
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization